### ISSUE TITLE
It is recommended to remove the check of return value or add switch.

### ISSUE THREAD

**Issue by tinybees** [mon4ter/sanic-jsonrpc#2]
**eg:**

1.
`
@jsonrpc.jrpc
async def sub(a: int, b: int) -> List[Dict[str, int]]:
    await asyncio.sleep(0.1)
    return [{"a": a, "b": b}]

`
Sub (5,2) is called correctly at this time

2.`

@jsonrpc.jrpc
async def sub(a: int, b: int) -> List[Dict[str, int]]:
    await asyncio.sleep(0.1)
    return [{"a": a, "b": b, "c": "c"}]

`

Call error at this time.
`feshttp.jsonrpc._routing.route.ResultError: invalid call result value [{'a': 5, 'b': 2, 'c': 'c'}]`

In my usage scenario, a lot of data is directly read from the database. There is no need to verify the type of return value. I just need to know that it is a Dict

Once verified, some performance will be lost, so I suggest that you can choose to turn on the verification function

**Comment by mon4ter** [comment]
Hi @tinybees!

You can override result type or don't use annotation at all to disable the check:
```python
@jsonrpc(result=Any)
async def sub(a: int, b: int) -> List[Dict[str, int]]:
    await asyncio.sleep(0.1)
    return [{"a": a, "b": b}]

@jsonrpc
async def sub(a: int, b: int):
    await asyncio.sleep(0.1)
    return [{"a": a, "b": b}]
```

I know, I must write the documentation on every feature, but I have lack of time to do it.

**Comment by tinybees** [comment]
OK，Thank you very much. @mon4ter
