### ISSUE TITLE
A jsonrpc package is missing from the 0.2.1 version and cannot be used.

### ISSUE THREAD

**Issue by tinybees** [mon4ter/sanic-jsonrpc#3]
Hi @mon4ter !

I tested the latest version (0.2.1) after installation and found that there was a 'jsronrpc' package missing.

The packages of the setup file are as follows.
```
    packages=[
        'sanic_jsonrpc',
        'sanic_jsonrpc._routing',
        'sanic_jsonrpc.models',
    ],
```

`missing 'sanic_jsonrpc.jsonrpc'`

 I will use version 0.1.1 first.

Thank you

**Comment by mon4ter** [comment]
Hi @tinybees !

Thank you! I've just released version 0.2.2.
